### ISSUE TITLE
Request for Access to Pre-trained Model Parameters

### ISSUE THREAD

**Issue by FengMingquan-sjtu** [HaoZhongkai/DPOT#1]
Dear Zhongkai,

I am currently working on project about neural PDE solver, and I have found DPOT is a strong SOTA baseline.  However, my computation resources are too limited to train it from scratch. 

Would it be possible for you to share the pre-trained model parameters? I believe It would greatly benefit my research and to the NeuralPDE community as well.  If there are any restrictions or conditions under which you would be willing to do so, I would be more than happy to discuss them.

I appreciate your consideration of my request and look forward to your positive response.

Best regards,
Mingquan

**Comment by HaoZhongkai** [comment]
Pre-trained models are uploaded at https://huggingface.co/hzk17/DPOT
